package com.nalvey.the_alvey_bank;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.Contact;
import io.swagger.v3.oas.annotations.info.License;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@OpenAPIDefinition (
	// attributes for annotations
	info = @Info(
		title = "The Alvey Bank",
		description = "Backend REST APIs for Banking Application",
		version = "v1.0",
		contact = @Contact(
				name = "Navid Alvey",
				email = "navidalvey@gmail.com",
				url = "https://github.com/NavidAlvey/BankingApplication"
			),
			license = @License(
				name = "The Alvey Bank",
				url = "https://github.com/NavidAlvey/BankingApplication"
			)
	),
	externalDocs = @ExternalDocumentation(
		description = "The Alvey Bank - Banking Application Documentation",
		url = "https://github.com/NavidAlvey/BankingApplication"
	)
)
// @EntityScan(basePackages = {"entity"})
@EnableJpaRepositories(basePackages = "com.nalvey.the_alvey_bank.repository")
@EntityScan(basePackages = "com.nalvey.the_alvey_bank.entity")
public class TheAlveyBankApplication {

	public static void main(String[] args) {
		SpringApplication.run(TheAlveyBankApplication.class, args);
	}

}
