package com.nalvey.the_alvey_bank;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
// @EntityScan(basePackages = {"entity"})
@EnableJpaRepositories(basePackages = "com.nalvey.the_alvey_bank.repository")
@EntityScan(basePackages = "com.nalvey.the_alvey_bank.entity")
public class TheAlveyBankApplication {

	public static void main(String[] args) {
		SpringApplication.run(TheAlveyBankApplication.class, args);
	}

}
